### ISSUE TITLE
Field won't update

### ISSUE THREAD

**Issue by bookercodes** [25th-floor/revalidation#12]
Hi there,

I am sure this is my error, but I cannot get my text input to update:

```tsx
import * as React from 'react'
import Revalidation from 'revalidation'


const SubmitForm = ({
  reValidation: { form, validate, valid, errors, validateAll },
  onSubmit
}) =>
  <form>
    <div className="formGroup">
      <label>Name</label>
      <input
        type="text"
        value={form.name}
        onChange={e => validate('name', e.target.value)}
      />
      {errors.name}
    </div>
    <p>{valid.toString()}</p>
    <button onClick={() => validateAll(onSubmit)}>Submit</button>
  </form>

const isGreaterThan = a => b => b > a
const ErrorComponent = ({ errorMsgs }) =>
  <div className="error">{errorMsgs.shift()}</div>
const validationRules = {
  name: [[isGreaterThan(5), `Minimum Name length of 6 is required.`]]
}
const initialState = { name: 'Alex' }
const enhanced = Revalidation(initialState, validationRules, ErrorComponent, {
  validateSingle: false
})
const EnhancedSubmitForm = enhanced(SubmitForm)

class SubmitPage extends React.Component<any, any> {
  constructor(props) {
    super(props)
    this.state = { form: { name: 'Alex' } }
  }
  onSubmit(e) {
    e.preventDefault()
    alert('submitted')
  }
  render() {
    return (
      <EnhancedSubmitForm onSubmit={this.onSubmit} form={this.state.form} />
    )
  }
}
export default SubmitPage

```

In the above example, I see the initial value `"Alex"` but when I type in that field, nothing happens? Looking at the [example](https://github.com/25th-floor/revalidation/blob/master/example/Components/SimpleForm.js
), I would have thought `reValidate.validate` would in turn update `reValidate.form.name`?

I am sure this is my understanding, hopefully I can contribute to the documentation after :)!

**Comment by busypeoples** [comment]
Your example is totally fine. `validate` returned a function when passing in a `name`, which works fine when using `compose` like f.e. `onChange={compose(validate('name'), getValue)}` but obviously will not working when calling it directly `validate('name', e.target.value)`.

`validate` is curried now, which means all variations work now:

 `validate('name', e.target.value)` 

 `validate(name)(e.target.value)` 

`compose(validate('name'), getValue)`

see [comit](https://github.com/25th-floor/revalidation/commit/aaa1d7162d5750a2c63930ed4638e3600d943125)

**Comment by bookercodes** [comment]
Thanks for all the help, @busypeoples, after applying the update my example now updates

However, once I enter a valid value, the error state does not go away:

![](https://www.dropbox.com/s/nlfdp7w0y2t48jt/Screenshot%202017-06-20%2009.30.40.png?dl=0)

**Comment by bookercodes** [comment]
Sorry, that is another "me" problem. I needed to to be comparing the `length` so I updated `isGreaterThan` to
```js
const isGreaterThan = a => b => b > a
```

And now it all works 🎉

**Comment by busypeoples** [comment]
Excellent, also I think you need a onSubmit on the form itself.
```
<form onSubmit={() => validateAll(onSubmit)}>
  <div className="formGroup">
    {/* ... */}
  </div>
  <p>{valid.toString()}</p>
  <button>Submit</button>
</form>
```

**Comment by bookercodes** [comment]
Oh yeah, that would explain why `validateAll` wasn't working ha - I moved `button.onClick` to `form.onSubmit` and now I have a nicely validated form
