### ISSUE TITLE
Asynchronous validation (remote validation)

### ISSUE THREAD

**Issue by bookercodes** [25th-floor/revalidation#14]
I have an asynchronous function,

```tsx
const videoExists = async wistiaId => {
  console.log('videoExists()')
  const response = await axios.get(`/api/videos/${wistiaId}`)
  const valid = !response.data.exists
  console.log('valid=', valid)
  return valid
}
```

Is it possible to validate an input using an asynchronous function? For example,

```tsx
const validationRules = {
  wistiaUrl: [[videoExists, 'Already exists']]
}
```

Using the trace messages, I can see this function is called (twice?),

```tsx
// from Chrome dev console...
submit?0c75934:21 videoExists()
submit?0c75934:21 videoExists()
2submit?0c75934:25 valid= true
submit?0c75934:21 videoExists()
submit?0c75934:21 videoExists()
2submit?0c75934:25 valid= false
```
But no matter if I return `true` or `false`, the `error.wistiaUrl` component is never showed

**Comment by busypeoples** [comment]
@bookercodes I would like avoiding any async actions inside the predicates, but your use case is excellent. Currently this is not handled via Spected and there is no recipe on how to handle this properly.
Let me think about how to tackle this scenario.

**Comment by busypeoples** [comment]
@bookercodes Also thanks for providing very valuable insights in the last couple of days!

**Comment by bookercodes** [comment]
Ah, is this because validators should be pure? (I am a functional programming noob!)

Really looking forward to see how you solve this, in the meantime I will work around this 👍

**Comment by busypeoples** [comment]
Closing this issue, as there seems a way to handle async validations now. We can still improve the current implementation later on.
