### ISSUE TITLE
Recommended pattern for calling e.preventDefault()

### ISSUE THREAD

**Issue by bookercodes** [25th-floor/revalidation#15]
I had/have this problem where when I submit a `form` like, this

```jsx
<form onSubmit={{validateAll(this.onSubmit)}}>
  <input type="submit" value="Submit" />
</form>
```

The validation errors would flash and then the _page_ would "redirect" from `/submit` to `/submit?`, clearing the state. Once on `/submit?`, the form validation works as you would expect, and does not submit until the form is valid. I don't really understand why but I don't think this is related to `revalidation`.

One thing I did notice is that none of the examples use `form` - they use a `div` and a custom `button.onClick` handler. Just curious about what the suggested pattern for calling `e.preventDefault()` is. I personally prefer to use a `form` as I find it to be a bit more semmantically correct.

**Comment by bookercodes** [comment]
At the moment, I just do this.

```
  <form
    onSubmit={e => {
      e.preventDefault()
      validateAll(onSubmit)
    }}
  >
```

Seems OK.

**Comment by busypeoples** [comment]
Yes, make sense. As soon as I have a recipe for handling async validations, I'll think about what a good approach could be.

**Comment by bookercodes** [comment]
👍

**Comment by bookercodes** [comment]
Are you based in Vienna by the way?

I just flew in to Vienna this evening for[ React Vienna](https://www.google.at/search?q=react+vienna&oq=react+vienna&aqs=chrome..69i57j69i60j0j69i60l2j69i59.1008j0j7&sourceid=chrome&ie=UTF-8) tomorrow  (we'll be filming it for the proect I run, [pusher.com/sessions](pusher.com/sessions))!

**Comment by busypeoples** [comment]
Yes, very cool!

**Comment by bookercodes** [comment]
Think this is solved :)

**Comment by busypeoples** [comment]
So this is still in user land right now. 
Except for `debounce` which takes care of calling preventDefault.

**Comment by bookercodes** [comment]
Yeah, and we want it to stay in userland, ye? It makes a lot of sense

**Comment by busypeoples** [comment]
Excellent!
