### ISSUE TITLE
Rename prop from "reValidation" to "revalidation"

### ISSUE THREAD

**Issue by bookercodes** [25th-floor/revalidation#25]
The repository is called `revalidation` but the prop is called `reValidation` 😕 

In my opinion, this is counter intuitive and can easily lead to someone writing,

```
const Component = ({revalidation: { ...) => ...
```

(lowercase `revalidation` instead of camel case `reValidation`)

And receiving an obscure error like,

```
TypeError: Cannot read property 'form' of undefined
```

Seems minor, but this can really trip someone up, especially when learning a new lib.

I suggest renaming the prop to `revalidation` so it is consistent with the repository and package name, what do you think?

**Comment by busypeoples** [comment]
Yes, makes a lot of sense.

**Comment by busypeoples** [comment]
Will be changed in 0.10
