### ISSUE TITLE
Do utility methods belong in another repo?

### ISSUE THREAD

**Issue by bookercodes** [25th-floor/revalidation#28]
Should `isValid`, `debounce`, etc. live elsewhere? 

I am torn because, on one hand, they can be really convenient

On the other hand, I feel like they are stand-alone utility functions and I like it when libraries are focused on one thing (for example, in Angular it came with `$http` service and if you wanted to use something custom, it always _felt_ redundant)

Just writing this issue quickly whilst it's on my mind so I haven't checked, but could `debounce` be replaced with [`debounce`](https://github.com/component/debounce) or [`lodash.debounce`](https://lodash.com/docs/#debounce)?

**Comment by bookercodes** [comment]
These same utility functions will probably work for the Inferno version, etc. too so it makes sense to abstract them?

**Comment by busypeoples** [comment]
It would be actually perfect if `debounce` would not be part of the library and one could an existing `utility` library. The problem right now, is that debounce internally has some logic, to decouple sync from async actions. So it does actually more than just delay the update.
