### ISSUE TITLE
No need to run async validator twice

### ISSUE THREAD

**Issue by bookercodes** [25th-floor/revalidation#29]
`validateAll` shouldn't need to run an asynchronous validator if the form is already valid 👍 

For example, if I have an empty form and write "foo", and the asynchronous validator returns `true`, there shouldn't be a need to run it again when I run `validateAll` in `onSubmit`. Running it again is redundant and causes a jarring delay.

**Comment by busypeoples** [comment]
Yes, valid point. So we should skip "revalidating" in this case.
I think we should write down some assumptions, just to make it clear how `revalidation` functions, just to prevent somebody from wanting to revalidate on a submit f.e.

**Comment by busypeoples** [comment]
Solved in `0.11`
