### ISSUE TITLE
Rename pending

### ISSUE THREAD

**Issue by bookercodes** [25th-floor/revalidation#31]
Need to have a think what the best alternative is, but I think `pending` should maybe be `loading`.

Normally, people call it a "loading indicator" not a "pending indicator", you know?

```js
const renderLoadingText = loading => {
   if (loading) {
     return <p>Loading...</p>
   }
}
```

**Comment by busypeoples** [comment]
Sure. Let's finalize the naming anyway. What do you think about `model` instead of `form`.
So `initializeModel` instead of `initializeState` and `revalidation: { model, errors, ... }` instead of `revalidation: {form, errors}` etc.

**Comment by bookercodes** [comment]
I dunno man, a model reminds me a lot of `MV*`

I also feel like a form is a type of model and the only type of model Revalidation is concerned with so `form` makes sense

`initialForm` instead of `initialState` could be nice but actually, I prefer `initialState` because it is the React terminology and hints that the HOC manages the form state (remember https://github.com/25th-floor/revalidation/issues/27 was a non-issue in the end)

So yeah, I probably wouldn't change it. WDYT?

**Comment by busypeoples** [comment]
Sounds great, then let's leave it as. So we'll change `pending` to `loading` and the other name changes defined in #30

**Comment by busypeoples** [comment]
Done, will be `0.10`
