### ISSUE TITLE
How to only validate when dirty?

### ISSUE THREAD

**Issue by bookercodes** [25th-floor/revalidation#33]
So, at the moment you can `validateOnChange` _immediately_ or validate on submit (i.e. `validateOnChange={false}`

Two other common use cases are,

* To not validate `onChange` _until_ the filed has been blurred (i.e. `onBlur`, i.e. when the field loses focus, i.e. when the field is dirty)
* To not validate `onChange` _until_ the form has been submitted (i.e. until`validateAll` has been called, i.e. when the form is dirty)

How can we go about doing this with Revalidation?

**Comment by busypeoples** [comment]
Yes, we need to figure this out, regarding the second case: has also been asked in #18 already,

**Comment by busypeoples** [comment]
Internally updateValue (exposed as `onChange`) accepts a third optional argument, where can define what should get updated(the field state, field errors and field async errors). We could enable to define what should happen when calling onChange optionally. This enables to separate the validation from the actual form field value update. Taking this approach would solve 1.
https://github.com/25th-floor/revalidation/blob/master/src/Revalidation.js#L149

**Comment by busypeoples** [comment]
All solved in `0.11`
