### ISSUE TITLE
Make validateOnChange false by default?

### ISSUE THREAD

**Issue by bookercodes** [25th-floor/revalidation#35]
Still need to think about this but I just wanted to jot down my thought early.

`validateOnChange` is `true` by default, which means `validateOnChange={true}` in the example is redundant. What's more, it is more idiomatic in React (in my opinion) to simply write `validateOnChange`, as in `<SomeForm validateOnChange>` 

What do you think about making `validateOnChange` `false` by default? To turn it on, you add `validateOnChange` prop, and to turn it off you can just remove it. No need for `{true}` or `{false}`. Can still assign computed value if needed like,`validateOnChange={this.shouldValidateOnChange}`

**Comment by busypeoples** [comment]
Yes, this makes a lot of sense. Let's add it to `0.11`.

**Comment by busypeoples** [comment]
See also #38. In `0.11` you will be able to pass in a function into `validateSingle` and `instantValidation` and depending on the current form state be able to define when instantValidation is set to true or false.
