### ISSUE TITLE
Support HTML in error text

### ISSUE THREAD

**Issue by bookercodes** [25th-floor/revalidation#36]
Imagine I want to bold something in my error message like,

```
const rules = {
  title: [notEmpty, '<strong>title cannot be empty</strong>']
}
```

Do I have to use `_dangerouslySetInnerHtml` here? 

In any case, we should make a recipe for this 👍

**Comment by busypeoples** [comment]
I haven't tried it out yet, but actually returning jsx might work.

**Comment by bookercodes** [comment]
You mean in the current version?

A more common use case would be putting a link (an `a`) in the text

**Comment by rostero1** [comment]
The following works:

```
const basicValidationRules = {
  name: [
    [ isNotEmpty, <span style={{ fontWeight: 'bold' }}>Name should not be empty.</span>, ],
  ],
};
```

**Comment by busypeoples** [comment]
This should work. Closing this issue.
