### ISSUE TITLE
Change validateOnChange pragmatically 

### ISSUE THREAD

**Issue by alexcroox** [25th-floor/revalidation#38]
I set validateOnChange to false by default as I think it's a pretty bad user experience to type a single character in an input for the first time and immediately be presented by errors. However, it is useful after they've clicked submit and validation errors appear, to have them auto disappear immediately as they correct their mistakes.

For this to happen I need to switch on validateOnChange after the first trigger of onSubmit(). Is this possible?

**Comment by busypeoples** [comment]
Yes, this will be possible in `0.11`. You will be able to pass in a function into the `instantValidation` attribute and have access to `submitted`, `errors` and other state information. So you will be able to write the following for example:
```js
<Form instantValidation={(submitted) => submitted} />
```
Which means as soon as the state updates to submitted being true, `instantValidation` is set to true in this specific example.

**Comment by alexcroox** [comment]
Sounds good thank you!

**Comment by busypeoples** [comment]
Added in `0.11`
