### ISSUE TITLE
onValidateAll?

### ISSUE THREAD

**Issue by alexcroox** [25th-floor/revalidation#39]
I have a long form and I need to scroll to the first error on submit button press, is there a function I can pass that gets called when a validation runs? With this I could scroll the page up to that error.

**Comment by busypeoples** [comment]
Will add to `0.11`.

**Comment by busypeoples** [comment]
Currently `validateAll` only runs a callback if the form is valid. We will enable to run functions after a validation independent of the validation outcome.

**Comment by alexcroox** [comment]
Great thanks! For now I'll just pass my own handler.

`onClick={() => { validateAll(onSubmit); onValidate(); }}>`

**Comment by busypeoples** [comment]
`validateAll` is called `onSubmit` now, and can handle any scenario. Callback after running the validation, will pass in a caculcated `valid`  as the complete `state`.
i.e.: 

```js
<button
  onClick={() => onSubmit(({form, valid}) => 
    valid ? submitCb(form) : console.log('something went wrong!')
  )}
>
  Submit
</button>
```
