### ISSUE TITLE
How to access validated form values after onChange

### ISSUE THREAD

**Issue by davidspiess** [25th-floor/revalidation#42]
Hi :) I want to access the (valid) form values `onChange` rather than `onSubmit`. How could that be accomplished?

At the moment i pass all form values up on every rerender:

```jsx
const Form = ({ revalidation: { form, onChange, valid }, onFormChange }) => (onFormChange(form, valid), (
  <form>
      <input type="number" min={1} max={20} value={form.zoom} onChange={compose(onChange('zoom'), parseInt, getValue)} />
  </form>
));
```

Is there a better way to do this? Maybe by composing a callback function in the `onChange` function after the validation passed?

**Comment by busypeoples** [comment]
Hi, I'll have a look at the problem later today.

**Comment by davidspiess** [comment]
Thats what i try to accomplish, yes :)

**Comment by busypeoples** [comment]
Make sense and will be added to `0.12`
