### ISSUE TITLE
Optional field validation

### ISSUE THREAD

**Issue by alexcroox** [25th-floor/revalidation#43]
I have a newPassword field, I'd only like to apply validation rules if the field isNotEmpty. Otherwise if it is blank it should pass validation (optional field). 

Is this possible?

**Comment by busypeoples** [comment]
Should actually work by defining a predicate function that checks if empty and if yes returns true else validates the input. i.e. Ramda `ifElse` function could work. But I'll build a real example later today.

**Comment by alexcroox** [comment]
Makes sense thank you, I came up with:

```
export const newPasswordValidationRule = [
  [isEmpty || isLengthGreaterThan(5), minimumMsg('Password', 6)]
]
```

**Comment by busypeoples** [comment]
Excellent!
