### ISSUE TITLE
React native support

### ISSUE THREAD

**Issue by batusai513** [25th-floor/revalidation#47]
Hi, I'm currently using this lib in a react native project with relatively ease but i've found out that i can't use the functions that rely on the `name` attribute being present on the input because there is no attribute name on a TextInput, it would be nice if we could send the property to update/validate as an argument instead on just relying on the `name` attribute.

Thanks for your hard work and awesome/mind-blowing code snippets.

**Comment by busypeoples** [comment]
Thank you very much for the feedback @batusai513 
The `onChange` function doesn't rely on any `name` attributes, but one would have to compose them, which might be a little overhead. 
```js
<input
  type="text"
  value={form.name}
  onChange={debounce.name(usernameExists, 1000)}
/>
```

I guess, we should adapt the `updateValueAndValidate` and the other shorthand functions to also accept a given `name`.

**Comment by busypeoples** [comment]
@batusai513 You can actually validate on blur. `onChange` accepts a third argument (will need to document it). There are constants that are exposed to via `revalidation`: `UPDATE_FIELD `, `VALIDATE_FIELD`, this is how the short hand functions work under the hood. 
I'll build an example.

**Comment by busypeoples** [comment]
@batusai513 did you find a way to solve your issue. With the latest revalidation release `0.12`, these problems should be solved.

**Comment by busypeoples** [comment]
Will close this issue. We can reopen if the problem arises again.

**Comment by batusai513** [comment]
@busypeoples well yeah, it was validating, the only thing was that it was validating on the first try, and it looked a bit weird, but it worked. thanks for your help :)

**Comment by busypeoples** [comment]
@batusai513 Excellent!
