### ISSUE TITLE
This does not support custom input element ?

### ISSUE THREAD

**Issue by zhangjunah** [25th-floor/revalidation#49]
I look the code，every element must be a \<input /\>, and has a 'name' attribute. But if I need a ‘multi checkboxes‘ , and it is valid only when more than 3 items be checked.  What can I do?

I see the `updateValue` and `updateValueAndValidate` calles a inner function `updateField `,  but this function has not been added to the `revalidationProp`, so I can't call it in my custom component.

I expect that I can write code like this: 

```
<MyComponent
    error={isValid(errors.demo)}
    value={form.demo}
    onChange={value => updateField('demo', value)}
/>
```

**Comment by busypeoples** [comment]
Can you create an example on codesandbox or somewhere else?
We can  solve this problem, but it would be could to see a running example first and verify against it.

**Comment by zhangjunah** [comment]
That is cool，the `onChange ` function has solved my problem，Thank you!
