### ISSUE TITLE
Remove initial state argument

### ISSUE THREAD

**Issue by busypeoples** [25th-floor/revalidation#5]
I think the `initialState` argument is unnecessary as the form values can be set via props anyway. 

This would mean changing `Revalidation(initialState, rules, errorCallback, options, Component) `
to `Revalidation(rules, errorCallback, options, Component)`.

Or are there any advantages by keeping the `initialState` argument?

**Comment by bookercodes** [comment]
I came here to ask the same thing! Not really sure how I'm meant to use it/why it is useful. I can just pass `{}` and everything works?

**Comment by busypeoples** [comment]
Exactly, we will simplify the API. I'm thinking of the following `Revalidation({ errorFn, ...}, rules, Component)`.
So only define a config object containing options like f.e. `validateSingle: true, errorFn` etc and the rules. 
I think this would simplify a couple of things.

**Comment by busypeoples** [comment]
See #23
