### ISSUE TITLE
Simplify onChange handling

### ISSUE THREAD

**Issue by busypeoples** [25th-floor/revalidation#7]
I think we can simplify the way the onChange inside the forms. Currently one has to manually compose the onChange listener. Instead of having to manually get the event and extract the value, this could be moved into into the `validate` function itself via composition or other ways.

Currently this might look something like this:

```js

const getValue = e => e.target.value

const Form = ({ reValidation : {form, validate, valid, errors = {}, validateAll}, onSubmit }) =>
  (
    <div className='form'>
      <input
        type='text'
        value={form.name}
        onChange={e => validate('name', getValue(e))}
      />
      <button onClick={() => validateAll(onSubmit)}>Submit</button>
    </div>
  )
```
Actually just passing in the field name would be enough, f.e.

```js

const getValue = e => e.target.value

const Form = ({ reValidation : {form, validate, valid, errors = {}, validateAll}, onSubmit }) =>
  (
    <div className='form'>
      <input
        type='text'
        value={form.name}
        onChange={validate('name')}
      />
      <button onClick={() => validateAll(onSubmit)}>Submit</button>
    </div>
  )
```

**Comment by davidspiess** [comment]
This woul be great 👍

**Comment by busypeoples** [comment]
Has been added to `0.11`
Added short cut functions for updating values, validating values as well as updating/validating.
